#!/bin/bash
#此脚本用来 拷贝 电池管家用
#制作者：陈云
#写于2014年3月 窝窝
#写于2014年4月 深圳语信公司
#写于2014年6月 深圳语信公司
#写于2014年7月 深圳云雀公司
PATH=/bin:/sbin:/usr/bin:usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin:~/yun
export PATH

make_Batterymonitor(){
	echo -e "\033[33m------batterymonitor------\033[0m"
	cd packages/BatteryManager
	echo -e "\033[32mcp $device/integers.xml common/res/values/integers.xml\033[0m"
	cp $device/integers.xml common/res/values/integers.xml
	b common
	echo -e "\033[32mout/common.apk ---> ../../out/$device/system/app/BatteryManager.apk\033[0m"
	mv out/common.apk ../../out/$device/system/app/BatteryManager.apk
	cd ../../	
}
