#!/bin/bash
#此脚本用来 DIY ROM 用
#制作者：陈云
#写于2014年3月 窝窝
#写于2014年4月 深圳语信公司
#写于2014年6月 深圳语信公司
#写于2014年7月 深圳云雀公司
PATH=/bin:/sbin:/usr/bin:usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin:~/yun
export PATH

make_Quick(){
	echo -e "\033[33m------QuickSearch------\033[0m"
	case "$device" in
		"la2w" )cd packages/QuickSearch/MSM8228;;
		"la3w" )cd packages/QuickSearch/MSM8228;;
		"la5w" )cd packages/QuickSearch/MT6592;;
	esac
	b QuickSearchBox
	mv out/QuickSearchBox.apk ../../../out/$device/system/app/QuickSearchBox.apk
		rmout
		cd ../../../
}