#!/bin/bash
#此脚本用来 DIY ROM 用
#制作者：陈云
#写于2014年3月 窝窝
#写于2014年4月 深圳语信公司
#写于2014年6月 深圳语信公司
#写于2014年7月 深圳云雀公司
PATH=/bin:/sbin:/usr/bin:usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin:~/yun
export PATH
make_framework-res(){
	echo -e "\033[33m------framework-res------\033[0m"
		cd framework/$CPU
		b framework-res
			echo -e "\033[32minstall out/framework-res.apk --> ../../out/$device/system/framework/framework-res.apk\033[0m"
			mv out/framework-res.apk ../../out/$device/system/framework/framework-res.apk
			rmout
			cd ../../
}
	