#!/bin/bash
#此脚本用来 DIY ROM 用
#制作者：陈云
#写于2014年3月 窝窝
#写于2014年4月 深圳语信公司
#写于2014年6月 深圳语信公司
#写于2014年7月 深圳云雀公司
PATH=/bin:/sbin:/usr/bin:usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin:~/yun
export PATH
#####################
app=app
#################
make_Settings(){
	echo -e "\033[33m------Settings------\033[0m"
		if [[ "$device" == "la2e" ]]; then
			cd packages/Settings/MSM8625Q
		elif [[  "$device"  == "la2l" ]]; then
			cd packages/Settings/MSM8926
		else
			cd packages/Settings/MSM8228
		fi
		b Settings
		mv out/Settings.apk ../../../out/$device/system/app/Settings.apk
		rmout
		cd ../../../
}
