#!/bin/bash
#此脚本用来 DIY ROM 用
#制作者：陈云
#写于2014年3月 窝窝
#写于2014年4月 深圳语信公司
#写于2014年6月 深圳语信公司
#写于2014年7月 深圳云雀公司
PATH=/bin:/sbin:/usr/bin:usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin:~/yun
export PATH

make_lockscreen(){
	echo -e "\033[33m------lockscreen------\033[0m"
		cd packages/lockscreen
		echo "cp $screen/default_layout.xml common/assets/default/default_layout.xml"
		cp $screen/appconfig.xml common/assets/appconfig.xml
		b common
		mv out/common.apk ../../out/$device/system/app/lockscreen.apk
		echo -e "\033[32mout/common.apk  -->../../out/$device/system/app/lockscreen.apk\033[0m"
		rmout
		cd ../../
}
