#!/bin/bash
#此脚本用来 DIY ROM 用
#制作者：陈云
#写于2014年3月 窝窝
#写于2014年4月 深圳语信公司
#写于2014年6月 深圳语信公司
#写于2014年7月 深圳云雀公司
PATH=/bin:/sbin:/usr/bin:usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin:~/yun
export PATH

make_browser(){
	echo -e "\033[33m------browser------\033[0m"
	cd packages/browser
	case $device in
		"la2e" )android="4.1";;
		"la2wmsm" )android="4.3";;
		"la5w" )android="4.4";;
		"la3w" )android="4.3";;
	esac
	b browser$android
	rmout
	mv out/browser$android.apk ../../out/$device/system/app/browser.apk
	cd ../../
}