#!/bin/bash
#此脚本用来 DIY ROM 用
#制作者：陈云
#写于2014年3月 窝窝
#写于2014年4月 深圳语信公司
#写于2014年6月 深圳语信公司
#写于2014年7月 深圳云雀公司
PATH=/bin:/sbin:/usr/bin:usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin:~/yun
export PATH
app=app
make_SystemUI(){
	echo -e "\033[33m------SysytemUI------\033[0m"
		echo $device
		echo "cd packages/SystemUI/$CPU "
		cd packages/SystemUI/$CPU
		b SystemUI
		echo -e "\033[32minstall out/SystemUI.apk---> ../../../out/$device/system/$app/SystemUI.apk\033[0m"
		mv out/SystemUI.apk ../../../out/$device/system/$app/SystemUI.apk
		rmout
		cd ../../../
}
